// AUTO-GENERATED — ported from the web app's assistantAudioManifest.ts,
// with each clip's public URL replaced by a bundled require() asset id.
// Do not edit by hand; regenerate from the web manifest if the clip library changes.
import type { AssistantClip } from './assistantAudioTypes';

export const ASSISTANT_VOICE = 'en-IN-NeerjaExpressiveNeural';

export const ASSISTANT_CLIPS: readonly AssistantClip[] = [
  { id: 'greeting-01', category: 'greeting', text: 'How can I help you?', src: require('../../../assets/assistant-audio/greeting/greeting-01.mp3') },
  { id: 'greeting-02', category: 'greeting', text: 'Hey, what\'s the problem? Tell me.', src: require('../../../assets/assistant-audio/greeting/greeting-02.mp3') },
  { id: 'greeting-03', category: 'greeting', text: 'What doubts do you have?', src: require('../../../assets/assistant-audio/greeting/greeting-03.mp3') },
  { id: 'greeting-04', category: 'greeting', text: 'I\'m listening. What\'s your question?', src: require('../../../assets/assistant-audio/greeting/greeting-04.mp3') },
  { id: 'greeting-05', category: 'greeting', text: 'Go ahead, ask me anything.', src: require('../../../assets/assistant-audio/greeting/greeting-05.mp3') },
  { id: 'greeting-06', category: 'greeting', text: 'Stuck somewhere? Tell me what\'s confusing you.', src: require('../../../assets/assistant-audio/greeting/greeting-06.mp3') },
  { id: 'greeting-07', category: 'greeting', text: 'Sure! What would you like to know?', src: require('../../../assets/assistant-audio/greeting/greeting-07.mp3') },
  { id: 'greeting-08', category: 'greeting', text: 'Okay, I\'m all ears. What\'s the doubt?', src: require('../../../assets/assistant-audio/greeting/greeting-08.mp3') },
  { id: 'greeting-09', category: 'greeting', text: 'Paused for a question? Go ahead, I\'m listening.', src: require('../../../assets/assistant-audio/greeting/greeting-09.mp3') },
  { id: 'greeting-10', category: 'greeting', text: 'Tell me, which part didn\'t make sense?', src: require('../../../assets/assistant-audio/greeting/greeting-10.mp3') },
  { id: 'greeting-11', category: 'greeting', text: 'Hi there! What can I clear up for you?', src: require('../../../assets/assistant-audio/greeting/greeting-11.mp3') },
  { id: 'greeting-12', category: 'greeting', text: 'Ask away, I\'m right here.', src: require('../../../assets/assistant-audio/greeting/greeting-12.mp3') },
  { id: 'greeting-13', category: 'greeting', text: 'What\'s on your mind? Go ahead.', src: require('../../../assets/assistant-audio/greeting/greeting-13.mp3') },
  { id: 'greeting-14', category: 'greeting', text: 'Something confusing? Just tell me.', src: require('../../../assets/assistant-audio/greeting/greeting-14.mp3') },
  { id: 'greeting-15', category: 'greeting', text: 'Yes, tell me your doubt.', src: require('../../../assets/assistant-audio/greeting/greeting-15.mp3') },
  { id: 'greeting-16', category: 'greeting', text: 'Hello! What would you like me to explain?', src: require('../../../assets/assistant-audio/greeting/greeting-16.mp3') },
  { id: 'greeting-17', category: 'greeting', text: 'No problem, let\'s sort it out. What\'s the question?', src: require('../../../assets/assistant-audio/greeting/greeting-17.mp3') },
  { id: 'greeting-18', category: 'greeting', text: 'Need a hand? Ask me your question.', src: require('../../../assets/assistant-audio/greeting/greeting-18.mp3') },
  { id: 'greeting-19', category: 'greeting', text: 'Alright, what\'s bothering you in this part?', src: require('../../../assets/assistant-audio/greeting/greeting-19.mp3') },
  { id: 'greeting-20', category: 'greeting', text: 'Happy to help. What\'s your doubt?', src: require('../../../assets/assistant-audio/greeting/greeting-20.mp3') },
  { id: 'greeting-end-01', category: 'greetingEnd', text: 'That\'s the end of the lecture! Any doubts?', src: require('../../../assets/assistant-audio/greeting-end/greeting-end-01.mp3') },
  { id: 'greeting-end-02', category: 'greetingEnd', text: 'And that wraps up the lecture. Anything you\'d like to ask?', src: require('../../../assets/assistant-audio/greeting-end/greeting-end-02.mp3') },
  { id: 'greeting-end-03', category: 'greetingEnd', text: 'Lecture done! Is anything still unclear?', src: require('../../../assets/assistant-audio/greeting-end/greeting-end-03.mp3') },
  { id: 'greeting-end-04', category: 'greetingEnd', text: 'Great job finishing the lecture! Any questions for me?', src: require('../../../assets/assistant-audio/greeting-end/greeting-end-04.mp3') },
  { id: 'greeting-end-05', category: 'greetingEnd', text: 'That\'s a wrap! Want me to explain anything again?', src: require('../../../assets/assistant-audio/greeting-end/greeting-end-05.mp3') },
  { id: 'greeting-end-06', category: 'greetingEnd', text: 'You made it to the end! Any doubts before you move on?', src: require('../../../assets/assistant-audio/greeting-end/greeting-end-06.mp3') },
  { id: 'greeting-end-07', category: 'greetingEnd', text: 'The lecture\'s over. Is there anything you\'d like to revisit?', src: require('../../../assets/assistant-audio/greeting-end/greeting-end-07.mp3') },
  { id: 'greeting-end-08', category: 'greetingEnd', text: 'Well done! Tell me if anything didn\'t click.', src: require('../../../assets/assistant-audio/greeting-end/greeting-end-08.mp3') },
  { id: 'greeting-end-09', category: 'greetingEnd', text: 'All done! Ask me anything about what you just watched.', src: require('../../../assets/assistant-audio/greeting-end/greeting-end-09.mp3') },
  { id: 'greeting-end-10', category: 'greetingEnd', text: 'That\'s it for this lecture. Any questions? I\'m listening.', src: require('../../../assets/assistant-audio/greeting-end/greeting-end-10.mp3') },
  { id: 'follow-up-01', category: 'followUp', text: 'Anything else you\'d like to ask?', src: require('../../../assets/assistant-audio/follow-up/follow-up-01.mp3') },
  { id: 'follow-up-02', category: 'followUp', text: 'Got another doubt? Go ahead.', src: require('../../../assets/assistant-audio/follow-up/follow-up-02.mp3') },
  { id: 'follow-up-03', category: 'followUp', text: 'Does that help? Ask me more if you like.', src: require('../../../assets/assistant-audio/follow-up/follow-up-03.mp3') },
  { id: 'follow-up-04', category: 'followUp', text: 'What else can I help you with?', src: require('../../../assets/assistant-audio/follow-up/follow-up-04.mp3') },
  { id: 'follow-up-05', category: 'followUp', text: 'Any other questions? I\'m listening.', src: require('../../../assets/assistant-audio/follow-up/follow-up-05.mp3') },
  { id: 'follow-up-06', category: 'followUp', text: 'Is there anything else that\'s unclear?', src: require('../../../assets/assistant-audio/follow-up/follow-up-06.mp3') },
  { id: 'follow-up-07', category: 'followUp', text: 'Want to dig deeper? Ask away.', src: require('../../../assets/assistant-audio/follow-up/follow-up-07.mp3') },
  { id: 'follow-up-08', category: 'followUp', text: 'Anything more on your mind?', src: require('../../../assets/assistant-audio/follow-up/follow-up-08.mp3') },
  { id: 'follow-up-09', category: 'followUp', text: 'Need me to explain something else?', src: require('../../../assets/assistant-audio/follow-up/follow-up-09.mp3') },
  { id: 'follow-up-10', category: 'followUp', text: 'Any follow-up questions? Just tell me.', src: require('../../../assets/assistant-audio/follow-up/follow-up-10.mp3') },
  { id: 'follow-up-11', category: 'followUp', text: 'Hope that cleared it up. What\'s next?', src: require('../../../assets/assistant-audio/follow-up/follow-up-11.mp3') },
  { id: 'follow-up-12', category: 'followUp', text: 'Still curious? Ask me another one.', src: require('../../../assets/assistant-audio/follow-up/follow-up-12.mp3') },
  { id: 'thinking-01', category: 'thinking', text: 'Got it, let me analyze your question.', src: require('../../../assets/assistant-audio/thinking/thinking-01.mp3') },
  { id: 'thinking-02', category: 'thinking', text: 'Okay, let me think about that.', src: require('../../../assets/assistant-audio/thinking/thinking-02.mp3') },
  { id: 'thinking-03', category: 'thinking', text: 'Good question! Give me a second.', src: require('../../../assets/assistant-audio/thinking/thinking-03.mp3') },
  { id: 'thinking-04', category: 'thinking', text: 'Alright, let me look into it.', src: require('../../../assets/assistant-audio/thinking/thinking-04.mp3') },
  { id: 'thinking-05', category: 'thinking', text: 'Hmm, let me check that for you.', src: require('../../../assets/assistant-audio/thinking/thinking-05.mp3') },
  { id: 'thinking-06', category: 'thinking', text: 'Understood. Let me work it out.', src: require('../../../assets/assistant-audio/thinking/thinking-06.mp3') },
  { id: 'thinking-07', category: 'thinking', text: 'Nice one! Let me find the answer.', src: require('../../../assets/assistant-audio/thinking/thinking-07.mp3') },
  { id: 'thinking-08', category: 'thinking', text: 'Okay, give me a moment.', src: require('../../../assets/assistant-audio/thinking/thinking-08.mp3') },
  { id: 'thinking-09', category: 'thinking', text: 'Let me go through the lecture material for that.', src: require('../../../assets/assistant-audio/thinking/thinking-09.mp3') },
  { id: 'thinking-10', category: 'thinking', text: 'Sure, let me figure this out.', src: require('../../../assets/assistant-audio/thinking/thinking-10.mp3') },
  { id: 'thinking-11', category: 'thinking', text: 'Great question. Let me take a look.', src: require('../../../assets/assistant-audio/thinking/thinking-11.mp3') },
  { id: 'thinking-12', category: 'thinking', text: 'Got your question. Working on it.', src: require('../../../assets/assistant-audio/thinking/thinking-12.mp3') },
  { id: 'thinking-13', category: 'thinking', text: 'One sec, let me find the best way to explain.', src: require('../../../assets/assistant-audio/thinking/thinking-13.mp3') },
  { id: 'thinking-14', category: 'thinking', text: 'Interesting! Let me dig into that.', src: require('../../../assets/assistant-audio/thinking/thinking-14.mp3') },
  { id: 'still-thinking-01', category: 'stillThinking', text: 'Almost there, just a moment.', src: require('../../../assets/assistant-audio/still-thinking/still-thinking-01.mp3') },
  { id: 'still-thinking-02', category: 'stillThinking', text: 'Still working on it, hang on.', src: require('../../../assets/assistant-audio/still-thinking/still-thinking-02.mp3') },
  { id: 'still-thinking-03', category: 'stillThinking', text: 'Just a few more seconds.', src: require('../../../assets/assistant-audio/still-thinking/still-thinking-03.mp3') },
  { id: 'still-thinking-04', category: 'stillThinking', text: 'Putting it all together, one moment.', src: require('../../../assets/assistant-audio/still-thinking/still-thinking-04.mp3') },
  { id: 'still-thinking-05', category: 'stillThinking', text: 'Hang tight, I\'m nearly done.', src: require('../../../assets/assistant-audio/still-thinking/still-thinking-05.mp3') },
  { id: 'still-thinking-06', category: 'stillThinking', text: 'This one needs a little more thought. Almost ready.', src: require('../../../assets/assistant-audio/still-thinking/still-thinking-06.mp3') },
  { id: 'still-thinking-07', category: 'stillThinking', text: 'Bear with me, it\'s coming together.', src: require('../../../assets/assistant-audio/still-thinking/still-thinking-07.mp3') },
  { id: 'still-thinking-08', category: 'stillThinking', text: 'Just finishing up, stay with me.', src: require('../../../assets/assistant-audio/still-thinking/still-thinking-08.mp3') },
  { id: 'still-thinking-09', category: 'stillThinking', text: 'Nearly there, thanks for waiting.', src: require('../../../assets/assistant-audio/still-thinking/still-thinking-09.mp3') },
  { id: 'still-thinking-10', category: 'stillThinking', text: 'Still on it. It won\'t be long.', src: require('../../../assets/assistant-audio/still-thinking/still-thinking-10.mp3') },
  { id: 'found-01', category: 'found', text: 'Found it! Here\'s what I\'ve got.', src: require('../../../assets/assistant-audio/found/found-01.mp3') },
  { id: 'found-02', category: 'found', text: 'Here you go!', src: require('../../../assets/assistant-audio/found/found-02.mp3') },
  { id: 'found-03', category: 'found', text: 'Okay, here\'s the answer.', src: require('../../../assets/assistant-audio/found/found-03.mp3') },
  { id: 'found-04', category: 'found', text: 'Got it! Let me explain.', src: require('../../../assets/assistant-audio/found/found-04.mp3') },
  { id: 'found-05', category: 'found', text: 'Alright, here\'s how it works.', src: require('../../../assets/assistant-audio/found/found-05.mp3') },
  { id: 'found-06', category: 'found', text: 'Here\'s what I found.', src: require('../../../assets/assistant-audio/found/found-06.mp3') },
  { id: 'found-07', category: 'found', text: 'Done! Take a look.', src: require('../../../assets/assistant-audio/found/found-07.mp3') },
  { id: 'found-08', category: 'found', text: 'There we go. Here\'s the explanation.', src: require('../../../assets/assistant-audio/found/found-08.mp3') },
  { id: 'found-09', category: 'found', text: 'Okay, this should help.', src: require('../../../assets/assistant-audio/found/found-09.mp3') },
  { id: 'found-10', category: 'found', text: 'Great, I\'ve got it. Here it is.', src: require('../../../assets/assistant-audio/found/found-10.mp3') },
  { id: 'found-11', category: 'found', text: 'Here\'s a clear way to think about it.', src: require('../../../assets/assistant-audio/found/found-11.mp3') },
  { id: 'found-12', category: 'found', text: 'Right, let\'s go through it.', src: require('../../../assets/assistant-audio/found/found-12.mp3') },
  { id: 'preparing-visual-01', category: 'preparingVisual', text: 'I\'m preparing a visual explanation. Read along meanwhile.', src: require('../../../assets/assistant-audio/preparing-visual/preparing-visual-01.mp3') },
  { id: 'preparing-visual-02', category: 'preparingVisual', text: 'A visual is on its way. Have a read while it loads.', src: require('../../../assets/assistant-audio/preparing-visual/preparing-visual-02.mp3') },
  { id: 'preparing-visual-03', category: 'preparingVisual', text: 'I\'m also making an animation for this. Read the answer meanwhile.', src: require('../../../assets/assistant-audio/preparing-visual/preparing-visual-03.mp3') },
  { id: 'preparing-visual-04', category: 'preparingVisual', text: 'Hang on, I\'m drawing this out for you. Read along for now.', src: require('../../../assets/assistant-audio/preparing-visual/preparing-visual-04.mp3') },
  { id: 'preparing-visual-05', category: 'preparingVisual', text: 'Your visual explanation is being prepared. Start reading meanwhile.', src: require('../../../assets/assistant-audio/preparing-visual/preparing-visual-05.mp3') },
  { id: 'preparing-visual-06', category: 'preparingVisual', text: 'Creating a quick animation. The text is ready to read.', src: require('../../../assets/assistant-audio/preparing-visual/preparing-visual-06.mp3') },
  { id: 'preparing-visual-07', category: 'preparingVisual', text: 'While I build the visual, go through the answer.', src: require('../../../assets/assistant-audio/preparing-visual/preparing-visual-07.mp3') },
  { id: 'preparing-visual-08', category: 'preparingVisual', text: 'A step-by-step visual is coming. Read ahead for now.', src: require('../../../assets/assistant-audio/preparing-visual/preparing-visual-08.mp3') },
  { id: 'preparing-visual-09', category: 'preparingVisual', text: 'I\'m turning this into a visual. It\'ll be ready shortly.', src: require('../../../assets/assistant-audio/preparing-visual/preparing-visual-09.mp3') },
  { id: 'preparing-visual-10', category: 'preparingVisual', text: 'Give the answer a read. The visual will follow soon.', src: require('../../../assets/assistant-audio/preparing-visual/preparing-visual-10.mp3') },
  { id: 'out-of-scope-01', category: 'outOfScope', text: 'Hmm, I couldn\'t find that in this subject\'s material. Try asking about this lecture.', src: require('../../../assets/assistant-audio/out-of-scope/out-of-scope-01.mp3') },
  { id: 'out-of-scope-02', category: 'outOfScope', text: 'That seems outside this subject. Could you ask something from the lecture?', src: require('../../../assets/assistant-audio/out-of-scope/out-of-scope-02.mp3') },
  { id: 'out-of-scope-03', category: 'outOfScope', text: 'I\'m not sure that\'s covered here. Try a question about this lecture.', src: require('../../../assets/assistant-audio/out-of-scope/out-of-scope-03.mp3') },
  { id: 'out-of-scope-04', category: 'outOfScope', text: 'That\'s a bit beyond this course. Ask me something from this lesson.', src: require('../../../assets/assistant-audio/out-of-scope/out-of-scope-04.mp3') },
  { id: 'out-of-scope-05', category: 'outOfScope', text: 'I can only help with this subject\'s material. Try another question?', src: require('../../../assets/assistant-audio/out-of-scope/out-of-scope-05.mp3') },
  { id: 'out-of-scope-06', category: 'outOfScope', text: 'Hmm, that\'s not in this course. Ask me about what you\'re studying here.', src: require('../../../assets/assistant-audio/out-of-scope/out-of-scope-06.mp3') },
  { id: 'out-of-scope-07', category: 'outOfScope', text: 'I don\'t see that in this subject. Could you ask it around the lecture?', src: require('../../../assets/assistant-audio/out-of-scope/out-of-scope-07.mp3') },
  { id: 'out-of-scope-08', category: 'outOfScope', text: 'That one\'s outside my notes for this course. Try something from the lecture.', src: require('../../../assets/assistant-audio/out-of-scope/out-of-scope-08.mp3') },
  { id: 'didnt-catch-01', category: 'didntCatch', text: 'Sorry, I didn\'t quite catch that. Could you say it again?', src: require('../../../assets/assistant-audio/didnt-catch/didnt-catch-01.mp3') },
  { id: 'didnt-catch-02', category: 'didntCatch', text: 'Hmm, I missed that. One more time?', src: require('../../../assets/assistant-audio/didnt-catch/didnt-catch-02.mp3') },
  { id: 'didnt-catch-03', category: 'didntCatch', text: 'I couldn\'t hear you clearly. Please try again.', src: require('../../../assets/assistant-audio/didnt-catch/didnt-catch-03.mp3') },
  { id: 'didnt-catch-04', category: 'didntCatch', text: 'Sorry, could you repeat that?', src: require('../../../assets/assistant-audio/didnt-catch/didnt-catch-04.mp3') },
  { id: 'didnt-catch-05', category: 'didntCatch', text: 'That was a bit unclear. Say it once more?', src: require('../../../assets/assistant-audio/didnt-catch/didnt-catch-05.mp3') },
  { id: 'didnt-catch-06', category: 'didntCatch', text: 'Pardon? I didn\'t get that.', src: require('../../../assets/assistant-audio/didnt-catch/didnt-catch-06.mp3') },
  { id: 'didnt-catch-07', category: 'didntCatch', text: 'Oops, I missed it. Please ask again.', src: require('../../../assets/assistant-audio/didnt-catch/didnt-catch-07.mp3') },
  { id: 'didnt-catch-08', category: 'didntCatch', text: 'Could you speak a little louder and try again?', src: require('../../../assets/assistant-audio/didnt-catch/didnt-catch-08.mp3') },
  { id: 'didnt-catch-09', category: 'didntCatch', text: 'I didn\'t catch the full question. Please repeat it.', src: require('../../../assets/assistant-audio/didnt-catch/didnt-catch-09.mp3') },
  { id: 'didnt-catch-10', category: 'didntCatch', text: 'Sorry, it cut out. Try once more?', src: require('../../../assets/assistant-audio/didnt-catch/didnt-catch-10.mp3') },
  { id: 'error-01', category: 'error', text: 'Oops, something went wrong on my side. Please try again.', src: require('../../../assets/assistant-audio/error/error-01.mp3') },
  { id: 'error-02', category: 'error', text: 'Sorry, I ran into a problem. Could you try that again?', src: require('../../../assets/assistant-audio/error/error-02.mp3') },
  { id: 'error-03', category: 'error', text: 'Hmm, that didn\'t work. Let\'s give it another shot.', src: require('../../../assets/assistant-audio/error/error-03.mp3') },
  { id: 'error-04', category: 'error', text: 'Something went wrong there. Please ask once more.', src: require('../../../assets/assistant-audio/error/error-04.mp3') },
  { id: 'error-05', category: 'error', text: 'Sorry, I hit a snag. Try again in a moment.', src: require('../../../assets/assistant-audio/error/error-05.mp3') },
  { id: 'error-06', category: 'error', text: 'Looks like a connection problem. Please try again.', src: require('../../../assets/assistant-audio/error/error-06.mp3') },
  { id: 'error-07', category: 'error', text: 'My apologies, I couldn\'t finish that. Please try again.', src: require('../../../assets/assistant-audio/error/error-07.mp3') },
  { id: 'error-08', category: 'error', text: 'That didn\'t go through. Could you ask again?', src: require('../../../assets/assistant-audio/error/error-08.mp3') },
  { id: 'still-there-01', category: 'stillThere', text: 'I\'m still here. Ask me anything, or type it below.', src: require('../../../assets/assistant-audio/still-there/still-there-01.mp3') },
  { id: 'still-there-02', category: 'stillThere', text: 'Take your time. I\'m listening whenever you\'re ready.', src: require('../../../assets/assistant-audio/still-there/still-there-02.mp3') },
  { id: 'still-there-03', category: 'stillThere', text: 'Still there? Go ahead and ask your question.', src: require('../../../assets/assistant-audio/still-there/still-there-03.mp3') },
  { id: 'still-there-04', category: 'stillThere', text: 'No rush. You can also type your question below.', src: require('../../../assets/assistant-audio/still-there/still-there-04.mp3') },
  { id: 'still-there-05', category: 'stillThere', text: 'I\'m ready when you are. Just speak up.', src: require('../../../assets/assistant-audio/still-there/still-there-05.mp3') },
  { id: 'still-there-06', category: 'stillThere', text: 'Didn\'t hear anything yet. Ask away, or type it instead.', src: require('../../../assets/assistant-audio/still-there/still-there-06.mp3') },
  { id: 'still-there-07', category: 'stillThere', text: 'Whenever you\'re ready, I\'m here to help.', src: require('../../../assets/assistant-audio/still-there/still-there-07.mp3') },
  { id: 'still-there-08', category: 'stillThere', text: 'Still with me? Tell me your doubt, or type it below.', src: require('../../../assets/assistant-audio/still-there/still-there-08.mp3') },
];
